feat: add destroy
This adds destroy (aliases: down, undeploy) which calls out to
client.RemoveService to remove services from the cluster. It is the
opposite of "deploy" (which now has the alias "up")

This was mostly cut&paste of existing functionality.

Cancelling the operation:

```
% ~miekg/uncloud/cmd/uncloud/uc destroy
NAME    MODE     REPLICAS
unkey   global   3

Proceed with destroy? [y/N] n

Destroy cancelled. No changes were made.
```

Giving a service:

```
 ~miekg/uncloud/cmd/uncloud/uc destroy ds
 Error: select services: no such service: ds
 ```

 Destroying takes place:
 ```

 ```
 NAME    MODE     REPLICAS
unkey   global   3

Proceed with destroy? [y/N] y

[+] Destroy service unkey 3/3
 ✔ Container unkey/cafab403586d on machine-11zv  Removed  3.9s
 ✔ Container unkey/f0773dc8c97d on machine-z00h  Removed  4.6s
 ✔ Container unkey/b1b428fabcd8 on machine-36i2  Removed  4.1s
 ```
Signed-off-by: Miek Gieben <miek@miek.nl>